# Generated by Django 4.1.7 on 2023-04-02 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allinone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cover_picture',
            new_name='picture',
        ),
    ]
